publishDir = "docs"
baseURL = "https://tokisaka23.github.io/tokisaka23-cloud/"
languageCode = "en-us"
title = "Tokisaka23 Cloud"
theme = "ananke"

[params]
  description = "Share game-extracted music files"
  readMore = false

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.mounts]]
    source = "content/notes"
    target = "content"
    type = "page"