publishDir = "docs"
baseURL = "https://tokisakabce.github.io/tokisaka23-cloud/"
languageCode = "en-us"
title = "Tokisaka23 Cloud"
theme = "ananke"
[params]
  description = "Share game-extracted music files"